/**
 * Production-ready, battle-tested .gitignore for Unreal Engine 5 projects
 * Excludes temporary caches, generated binaries, and user settings,
 * preventing hundreds of gigabytes from being mistakenly uploaded.
 */
export const UE5_GITIGNORE = `# =======================================
# Unreal Engine 5 Recommended .gitignore
# Generated by UnrealSync
# =======================================

# Visual Studio & IDE temporary files
.vs/
*.VC.db
*.opendb
*.sln
*.vcxproj
*.vcxproj.filters
*.user
.idea/
.vscode/

# Unreal Engine Temporary & Generated Folders
Binaries/
DerivedDataCache/
Intermediate/
Saved/

# Plugins temporary folders
Plugins/*/Binaries/
Plugins/*/Intermediate/

# Engine build artifacts
Build/
LocalBuilds/

# Autogenerated files
*.patch
*.diff

# Package builds (optional outputs)
Package/
Packages/
StagedBuilds/

# OS specific files
.DS_Store
Thumbs.db
Desktop.ini
$RECYCLE.BIN/

# Unreal Engine Crash Reports & Logs
*.log
*.dmp
*.crashinfo

# Source Control Temporary Backups generated by UnrealSync
Saved/Conflict_Backups/
`;
