/**
 * .gitattributes template for Unreal Engine 5
 * Ensures binary files are handled properly and prevents CRLF corruption
 */
export const UE5_GITATTRIBUTES_STANDARD = `# =======================================
# Unreal Engine 5 .gitattributes
# Generated by UnrealSync
# =======================================

# Auto detect text files and perform LF normalization
* text=auto

# C++ Source Code & Headers
*.cpp text diff=cpp
*.h text diff=cpp
*.c text diff=cpp
*.cs text diff=csharp
*.ini text
*.txt text
*.json text
*.xml text
*.uproject text

# Unreal Engine Binary Assets (Prevent line ending conversion)
*.uasset binary
*.umap binary
*.fbx binary
*.obj binary
*.png binary
*.jpg binary
*.jpeg binary
*.tga binary
*.psd binary
*.exr binary
*.hdr binary
*.wav binary
*.mp3 binary
*.ogg binary
*.dll binary
`;

export const UE5_GITATTRIBUTES_LFS = `# =======================================
# Unreal Engine 5 .gitattributes (With Git LFS)
# Generated by UnrealSync
# =======================================

* text=auto

*.cpp text diff=cpp
*.h text diff=cpp
*.ini text
*.uproject text

# Git LFS tracking for heavy game assets
*.uasset filter=lfs diff=lfs merge=lfs -text
*.umap filter=lfs diff=lfs merge=lfs -text
*.fbx filter=lfs diff=lfs merge=lfs -text
*.obj filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text
*.exr filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
`;
